[package]
name = "Cyptara_Conquest_Movement"
version = "1.0.0"
license = "MIT"
authors = []

[addresses]
resource_publisher = "0xa40f392c12d1e02e56703b143f6f74a826e4ff0a5c0585ab739096c883e9fe7e"
publisher = "0xdc494026c03645c91f7ad28a5119c34d4001329c15e98e446485a4cef48bb9ff" #unity

[dev-addresses]
publisher = "0xdc494026c03645c91f7ad28a5119c34d4001329c15e98e446485a4cef48bb9ff"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "devnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.AptosTokenObjects]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "devnet"
subdir = "aptos-move/framework/aptos-token-objects"

[dev-dependencies]
