[package]
name = "Cyptara_Conquest_Movement"
version = "1.0.0"
license = "MIT"
authors = []

[addresses]
resource_publisher = "0xa85ebfda0f61c63a85c6b103d32f2251d1736a7ce36f680f040fb493e0fb604f"
publisher = "0x725790d90e8f68a25caabea7da90744e8c172a9dcb2a2aa4ddf23441f414c5c5" #unity

[dev-addresses]
publisher = "0x725790d90e8f68a25caabea7da90744e8c172a9dcb2a2aa4ddf23441f414c5c5"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "devnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.AptosTokenObjects]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "devnet"
subdir = "aptos-move/framework/aptos-token-objects"

[dev-dependencies]
