[package]
name = "Cyptara_Conquest_Movement"
version = "1.0.0"
license = "MIT"
authors = []

[addresses]
resource_publisher = "0xa85ebfda0f61c63a85c6b103d32f2251d1736a7ce36f680f040fb493e0fb604f"
publisher = "0x95bf273a0f9352b41ab32fa66a9fcea23264d8db812f61e5f4424677b51b55a" #unity

[dev-addresses]
publisher = "0x95bf273a0f9352b41ab32fa66a9fcea23264d8db812f61e5f4424677b51b55a"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "devnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.AptosToken]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "devnet"
subdir = "aptos-move/framework/aptos-token"

[dev-dependencies]
